Implement ABSL_INTERNAL_DISABLE_DEPRECATED_DECLARATION_WARNING for MS compiler
this change fixes errors emitted by MS compiler:
```
1>C:\abseil-cpp\absl\meta\type_traits.h(292,15): error C4996: 'std::aligned_storage<_Len,_Align>': warning STL4034: std::aligned_storage and std::aligned_storage_t are deprecated in C++23. Prefer alignas(T) std::byte t_buff[sizeof(T)]. You can define _SILENCE_CXX23_ALIGNED_STORAGE_DEPRECATION_WARNING or _SILENCE_ALL_CXX23_DEPRECATION_WARNINGS to suppress this warning.
```