absl/status: Fix build on AIX
`_LINUX_SOURCE_COMPAT` needs to be defined to fix

    absl/status/status.cc:494:5: error: duplicate case value
      494 |     case ENOTEMPTY:   // Directory not empty
          |     ^~~~
    absl/status/status.cc:480:5: note: previously used here
      480 |     case EEXIST:         // File exists
          |     ^~~~