Downgrade to rules_cc 0.0.17 because 0.1.0 was yanked
Note that the error message says downgrade to 0.0.15, but I'm not sure
why. 0.0.17 is the latest.

```
ERROR: Error computing the main repository mapping: Yanked version detected in your resolved dependency graph: rules_cc@0.1.0, for the reason: rules_cc 0.1.0 is yanked due to incompatible change (prematurely removing cc_proto_library from defs.bzl), please downgrade to 0.0.15.
```
PiperOrigin-RevId: 716675841
Change-Id: I459c35186161cc3d10b8c38973041d9a592c7cec