Use `#ifdef` to avoid errors when `-Wundef` is used.
Example:
absl/hash/internal/hash.h:342:5: error: 'ABSL_HAVE_INTRINSIC_INT128' is not defined, evaluates to 0 [-Werror,-Wundef]
  342 | #if ABSL_HAVE_INTRINSIC_INT128
PiperOrigin-RevId: 706686332
Change-Id: I77639ba4826ea7a40f3f05e9885c795db3376ddd