container/internal: Explicitly include <cstdint>
GCC 15 will no longer include <cstdint> by default, resulting in build
failures in projects that do not explicitly include it.

Error:
absl/container/internal/container_memory.h:66:27: error: ‘uintptr_t’ does not name a type
   66 |   assert(reinterpret_cast<uintptr_t>(p) % Alignment == 0 &&
      |                           ^~~~~~~~~
absl/container/internal/container_memory.h:31:1: note: ‘uintptr_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   30 | #include "absl/utility/utility.h"
  +++ |+#include <cstdint>
   31 |

See-also: https://gcc.gnu.org/pipermail/gcc-cvs/2024-August/407124.html
Signed-off-by: Christopher Fore <csfore@posteo.net>