PR #1835: Bump deployment_target version and add visionos to podspec
Imported from GitHub PR https://github.com/abseil/abseil-cpp/pull/1835

Add visionos support.

Bump deployment_target versions to supported version, e.g.
'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 18.2.99.

This also fixes podspec validation error:
xcodebuild:  abseil/absl/base/internal/thread_identity.h:238:24: error: thread-local storage is not supported for the current target

CC: @sampajano

Merge c947899596ede744487f597bae123bfb6a3531b9 into 0f0a77270348ae16b06d23cc6ecc22923a590cc7

Merging this change closes #1835

COPYBARA_INTEGRATE_REVIEW=https://github.com/abseil/abseil-cpp/pull/1835 from HannahShiSFB:bump-podspec-deployment-target-version c947899596ede744487f597bae123bfb6a3531b9
PiperOrigin-RevId: 726522669
Change-Id: Id2ca85528474d77e8f8f334c2358b47229b378c5